version: '3'
services:
  matches:
    image: matches-ms
    ports:
      - "5000:5000"
    networks:
      - pad
    hostname: matches-hostname
  matches2:
    image: matches-ms
    ports:
      - "5002:5000"
    networks:
      - pad
    hostname: matches-hostname-2
  matches-db:
    image: postgres
    restart: always
    ports:
      - "5435:5432"
    environment:
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_USER: admin
      POSTGRES_DB: matches_db
    hostname: matches-db
    networks:
      - pad
    volumes:
      - ./init-scripts-matches:/docker-entrypoint-initdb.d
  weather:
    image: weather-ms
    ports:
      - "5001:5001"
    networks:
      - pad
    hostname: weather-hostname
  weather2:
    image: weather-ms
    ports:
      - "5003:5001"
    networks:
      - pad
    hostname: weather-hostname-2
  weather-db:
    image: postgres
    restart: always
    ports:
      - "5434:5432"
    environment:
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_USER: admin
      POSTGRES_DB: weather_db
    hostname: weather-db
    networks:
      - pad
    volumes:
      - ./init-scripts-weather:/docker-entrypoint-initdb.d
  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
  grafana:
    image: grafana/grafana
    volumes:
      - ./datasource.yaml:/etc/grafana/provisioning/datasources/datasource.yaml
    ports:
      - "3000:3000"
  gateway:
    image: gateway
    ports:
      - "8080:8080"
    networks:
      - pad
networks:
  pad:
    external:
      name: pad